server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football_world
    username: root
    password: 962867042zrb
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 962867042zrb


mybatis:
  configuration:
    # 将sql语句打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  # 给实体类其别名 - 类名小写
  type-aliases-package: com.zrb41.pojo